[workspace]
resolver = "2"
members = [
    "bps",
    "datachannel-wrapper",
    "hqx",
    "input-helper",
    "mgba",
    "mmpx",
    "tango",
    "tango-dataview",
    "tango-filesync",
    "tango-gamedb",
    "tango-pvp",
    "tango-replaytool",
    "tango-signaling",
    "tango-signaling-server",
]

[workspace.lints.clippy]
new_without_default = "allow"
type_complexity = "allow"
identity_op = "allow"
blocks_in_conditions = "allow"
redundant_closure = "allow"
too_many_arguments = "allow"
