[workspace]
resolver = "2"
members = ["mgba", "tango-core", "tango-matchmaking", "mgba-sys"]

[patch.crates-io]
webrtc-util = { git = "https://github.com/webrtc-rs/util", rev = "2d193c0fd146e4d48ce63d07dbd085702b60aac2" }
